spring:
  application:
    name: ConjuntosBack
  
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:conjuntosdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console

# JWT Configuration
jwt:
  secret: 12345678901234567890123456789012
  expiration: 3600000