spring:
  application:
    name: ConjuntosBack

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/vecinos_conectados?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: PasswordDB

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT Configuration
jwt:
  secret: 12345678901234567890123456789012
  expiration: 3600000
